Pacagroup.Comercial.Creditos.WebConsumer/Models/Cliente/ClienteViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Pacagroup.Comercial.Creditos.WebConsumer.Models.Cliente
{
    public class ClienteViewModel
    {
        public int IdCliente { get; set; }
        public string Nombre { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string TipoDocumento { get; set; }
        public string NumeroDocumento { get; set; }
        public string Sexo { get; set; }
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime FechaNac { get; set; }
        public string Direccion { get; set; }
        public string CodigoPostal { get; set; }
        public string EstadoCivil { get; set; }
    }
}

Pacagroup.Comercial.Creditos.WebConsumer/Controllers/ClienteController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Runtime.Serialization.Json;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Pacagroup.Comercial.Creditos.WebConsumer.Models.Cliente;
using Pacagroup.Comercial.Creditos.WebConsumer.Models.Credito;

namespace Pacagroup.Comercial.Creditos.WebConsumer.Controllers
{
    public class ClienteController : Controller
    {
        // GET: Cliente
        public async Task<ActionResult> Index(string apellidoPaterno)
        {
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost/");
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                if (string.IsNullOrEmpty(apellidoPaterno))
                    apellidoPaterno = string.Empty;

                var cliente = new ClienteViewModel { ApellidoPaterno = apellidoPaterno };

                DataContractJsonSerializer ser = new DataContractJsonSerializer(typeof(ClienteViewModel));
                MemoryStream men = new MemoryStream();
                ser.WriteObject(men, cliente);
                string data = Encoding.UTF8.GetString(men.ToArray(), 0, (int)men.Length);

                HttpResponseMessage res =
                    await
                        client.PostAsync("WcfServiceCliente/ClienteService.svc/rest/BuscarCliente",
                            new StringContent(data, Encoding.UTF8, "application/json"));

                if (res.IsSuccessStatusCode)
                {
                    var result = res.Content.ReadAsStreamAsync().Result;
                    DataContractJsonSerializer obj = new DataContractJsonSerializer(typeof(List<ClienteViewModel>));
                    List<ClienteViewModel> response = obj.ReadObject(result) as List<ClienteViewModel>;
                    return View(response);
                }
                else
                    return View();
            }
        }
    }
}

Pacagroup.Comercial.Creditos.WebConsumer/Views/Cliente/Index.cshtml
@model IEnumerable<Pacagroup.Comercial.Creditos.WebConsumer.Models.Cliente.ClienteViewModel>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

@using (Html.BeginForm("Index", "Cliente", FormMethod.Get))
{
    <p>
        Buscar por Apellido Paterno: @Html.TextBox("apellidoPaterno", ViewBag.CurrentFilter as string)
        <input type="submit" value="Buscar" />
    </p>
}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.IdCliente)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ApellidoPaterno)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ApellidoMaterno)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TipoDocumento)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NumeroDocumento)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Sexo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FechaNac)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Direccion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CodigoPostal)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EstadoCivil)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.IdCliente)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ApellidoPaterno)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ApellidoMaterno)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TipoDocumento)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NumeroDocumento)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Sexo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FechaNac)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Direccion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CodigoPostal)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EstadoCivil)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
}

</table>